# =============================================================================
# MACHINE CONFIGURATION: ARASAKA
# =============================================================================
# Machine-specific NixOS configuration for the "arasaka" system
#
# MACHINE SPECS:
# - Desktop/workstation
# - NVIDIA GPU (requires proprietary drivers)
# - Niri window manager setup
#
# PURPOSE:
# This file overrides and extends the base system configuration
# (system/configuration.nix) with machine-specific settings
#
# WHAT GOES HERE:
# - Hardware-specific configuration
# - Machine-specific services
# - Host-specific networking
# - Desktop environment choices
# - Performance tuning for this hardware
#
# IMPORTS:
# - hardware-configuration.nix: Auto-generated hardware detection
# - nvidia.nix: NVIDIA driver and optimization settings
# - ../../wm/niri.nix: Niri window manager system integration
# =============================================================================
{ config, lib, pkgs, ... }:

{
  # ---------------------------------------------------------------------------
  # MACHINE IDENTIFICATION
  # ---------------------------------------------------------------------------
  # Hostname for this machine
  # Must match the entry in outputs/os.nix 'hosts' list
  networking.hostName = "arasaka";

  # ---------------------------------------------------------------------------
  # MODULE IMPORTS
  # ---------------------------------------------------------------------------
  # Load machine-specific configuration modules
  imports = [ 
    # Hardware configuration (generated by nixos-generate-config)
    # Contains: boot device, file systems, swap, CPU/GPU detection
    ./hardware-configuration.nix
    
    # NVIDIA GPU driver configuration and Wayland optimizations
    # Configures: proprietary drivers, modesetting, power management
    ./nvidia.nix
    
    # Niri window manager system integration
    # Provides: niri-session, greetd login, systemd services, portals
    ../../wm/niri.nix
  ];

  # ---------------------------------------------------------------------------
  # MACHINE-SPECIFIC OVERRIDES
  # ---------------------------------------------------------------------------
  # Add machine-specific settings here that override base configuration
  # Examples:
  #
  # - Different kernel version:
  #   boot.kernelPackages = pkgs.linuxPackages_latest;
  #
  # - Enable X11 for fallback:
  #   services.xserver.enable = true;
  #
  # - Machine-specific services:
  #   services.printing.enable = true;
  #
  # - Custom boot options:
  #   boot.loader.grub.device = "/dev/sda";
  #
  # - Network configuration:
  #   networking.interfaces.eth0.useDHCP = true;
  # ---------------------------------------------------------------------------
}
