# =============================================================================
# SOPS CONFIGURATION
# =============================================================================
# Defines which keys can decrypt which secrets
#
# SETUP:
# 1. Generate age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Get public key: age-keygen -y ~/.config/sops/age/keys.txt
# 3. Replace YOUR_AGE_PUBLIC_KEY_HERE with the output
# 4. Create/edit secrets: sops secrets/secrets.yaml
# =============================================================================

keys:
  # Master age key (shared across all machines via Bitwarden)
  - &master age1egtznjsswt6a2f6mxqyhj6n3c9c4v6c678k3tc7deqr8ua78apusegrves

creation_rules:
  # All secrets in secrets/ directory are encrypted to the master key
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *master
