# =============================================================================
# ASTHENIA FLAKE CONFIGURATION
# =============================================================================
# This is the main entry point for the entire NixOS configuration.
#
# FLAKE STRUCTURE:
# - inputs: External dependencies (nixpkgs, home-manager, window managers, etc.)
# - outputs: Generated configurations (NixOS systems, Home Manager profiles)
#
# KEY ARCHITECTURAL DECISIONS:
# 1. Standalone Home Manager: User configs are independent of system configs
# 2. Overlay-based builders: Custom builder functions injected via overlays
# 3. Flake schemas: Enhanced documentation and validation
# 4. Modular inputs: Each feature (niri, dms, nvf) has its own input
#
# USAGE:
# - System: sudo nixos-rebuild switch --flake .#arasaka
# - User: home-manager switch --flake .#niri
# - Build test: nix build .#nixosConfigurations.arasaka.config.system.build.toplevel
# =============================================================================
{
  description = "NixOS Configuration with Home Manager";

  # =============================================================================
  # BINARY CACHE CONFIGURATION
  # =============================================================================
  # Pre-built binaries significantly speed up rebuilds by avoiding compilation
  # These settings configure which binary caches to use and trust
  nixConfig = {
    # Binary cache servers to fetch pre-built packages from
    extra-substituters = [
      "https://cache.nixos.org"
    ];
    # Public keys for verifying downloaded binaries
    extra-trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];
  };

  # =============================================================================
  # FLAKE INPUTS
  # =============================================================================
  # External dependencies that this flake depends on
  # Each input is pinned to a specific revision for reproducibility
  inputs = {
    # --- Core System Inputs ---
    
    # NixOS packages repository (unstable channel for latest packages)
    # Using shallow clone to reduce disk space and speed up updates
    nixpkgs.url = "git+https://github.com/NixOS/nixpkgs?shallow=1&ref=nixos-unstable";

    # Home Manager - manages user-level configurations and dotfiles
    # Follows nixpkgs to ensure package version compatibility
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Flake schemas - provides enhanced documentation and structure validation
    flake-schemas.url = "github:DeterminateSystems/flake-schemas";

    # --- Window Manager and Desktop Environment ---
    
    # Niri - scrollable-tiling Wayland compositor
    # Provides both NixOS module and overlay for system integration
    niri-flake = {
      url = "github:sodiboo/niri-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # DMS (Dank Material Shell) - system monitoring and widget framework
    # Provides both NixOS and Home Manager modules for dual-level config
    dms = {
      url = "github:AvengeMedia/DankMaterialShell";
    };
    
    # --- Application Inputs ---
    
    # neovim-flake - Neovim configuration framework with modular plugin system
    # Provides homeManagerModules for user-level editor setup
    neovim-flake = {
      url = "github:infktd/neovim-flake";
    };

    # nixcord - Discord client with custom themes and plugins
    nixcord = {
      url = "github:kaylorben/nixcord";
    };

  };

  # =============================================================================
  # FLAKE OUTPUTS
  # =============================================================================
  # The actual configurations generated by this flake
  # Each output type serves a different purpose in the Nix ecosystem
  outputs = inputs @ { self, nixpkgs, home-manager, flake-schemas, neovim-flake, ... }:
    let
      # Target system architecture (most desktop/laptop systems)
      system = "x86_64-linux";

      # --- OVERLAY SYSTEM ---
      # Overlays extend nixpkgs with custom packages and modifications
      # Our overlays add builder functions that create configs programmatically
      # See lib/overlays.nix for implementation details
      overlays = import ./lib/overlays.nix { inherit inputs system; };

      # --- PACKAGE SET CONFIGURATION ---
      # Create a customized nixpkgs instance with:
      # 1. Our custom overlays (adds builder functions)
      # 2. System architecture specification
      # 3. Unfree packages enabled (needed for NVIDIA drivers, Discord, etc.)
      pkgs = import nixpkgs {
        inherit overlays system;
        config = {
          allowUnfree = true;  # Required for proprietary software
        };
      };
    in
    {
      # --- HOME MANAGER CONFIGURATIONS ---
      # User-level configurations (dotfiles, programs, themes)
      # Built and activated independently from system configs
      #
      # Available profiles:
      # - default: Basic user config without window manager
      # - niri: Full desktop environment with Niri WM
      #
      # Build: nix build .#homeConfigurations.<name>.activationPackage
      # Switch: home-manager switch --flake .#<name>
      homeConfigurations = pkgs.builders.mkHome { };

      # --- NIXOS SYSTEM CONFIGURATIONS ---
      # System-level configurations (kernel, drivers, services)
      # One configuration per machine (currently just "arasaka")
      #
      # Build: nix build .#nixosConfigurations.<hostname>.config.system.build.toplevel
      # Switch: sudo nixos-rebuild switch --flake .#<hostname>
      # Test: sudo nixos-rebuild test --flake .#<hostname>
      nixosConfigurations = pkgs.builders.mkNixos { };

      # --- CUSTOM EXPORTS ---
      # Export pkgs and overlays for use by other flakes or tools
      # This allows external consumers to use our custom packages and functions
      out = { inherit pkgs overlays; };

      # --- FLAKE SCHEMAS ---
      # Metadata describing the structure of this flake's outputs
      # Improves documentation and enables better tooling integration
      # Merges standard schemas with our custom schema definitions
      schemas =
        flake-schemas.schemas //
        import ./lib/schemas.nix { inherit (inputs) flake-schemas; };
    };
}